# Generated by Django 4.1.5 on 2023-01-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointmenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateField()),
                ('Departement', models.CharField(max_length=50)),
                ('Number', models.BigIntegerField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
