# Generated by Django 4.1.5 on 2023-01-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_commenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
