# Generated by Django 4.1.5 on 2023-02-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_registertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertable',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
